version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: mdshop-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306

    webserver:
        build:
            context: .
            dockerfile: docker/ci/nginx/Dockerfile
        container_name: mdshop-webserver
        ports:
            - 80:80

    php-fpm:
        build:
            context: .
            dockerfile: docker/ci/php-fpm/Dockerfile
        container_name: mdshop-php-fpm
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
