version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: mdshop-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306

    webserver:
        build:
            context: .
            dockerfile: docker/ci/nginx/Dockerfile
        container_name: mdshop-webserver
        ports:
            - 80:80

    php-fpm:
        image: ksardas/mdshop:latest
        container_name: mdshop-php-fpm
        volumes:
            - ./public/uploads/invoice:/application/public/uploads/invoice
        environment:
            - APP_ENV=prod
            - APP_SECRET=39d9d81c43a1571fe868ad211409c78a
            - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
            - MAILER_URL=${MAILER_URL}
            - MAILER_SENDER=${MAILER_SENDER}
            - MAILER_RECIPIENT=${MAILER_RECIPIENT}
