version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.1-r1
            pip install docker-compose==1.19.0
      - run:
          name: Build containers and push application to Docker Hub
          command: |
            docker-compose -f docker-compose.ci.yml up -d --build --force-recreate
            docker-compose -f docker-compose.ci.yml ps
            docker commit mdshop-php-fpm ksardas/mdshop:$CIRCLE_SHA1
            docker commit mdshop-php-fpm ksardas/mdshop:latest
            docker images
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker push $DOCKER_HUB_USER_ID/mdshop:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/mdshop:latest

