<?php

namespace App\Controller;

use App\Service\XlsProcessor;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Invoice;

/**
 * @Route(name="invoice.")
 */
class InvoiceController extends AbstractController {
    /**
     * @Route("/invoice", name="list")
     * @Method("GET")
     * @return Response
     * @throws \LogicException
     */
    public function list(): Response
    {
        return $this->render('base.html.twig');
    }

    /**
     * @Route("/generate", name="generate")
     * @Method("GET")
     * @param XlsProcessor $xlsProcessor
     * @return Response
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     */
    public function generate(XlsProcessor $xlsProcessor): Response
    {
        $spreadsheet = $xlsProcessor->createSpreadSheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setCellValue(
            'A1',
            'Generated by ' . $this->getUser()->getUsername()
        );
        $fileName = $this->getUser()->getUsername() . '_' . date('dmY') . '.xls';
        $xlsProcessor->save(
            $spreadsheet,
            'invoice',
            $fileName
        );

        $directory = $this->getParameter('uploads_directory') . '/' . 'invoice';
        return $this->file($directory . '/' . $fileName);
    }
}
