<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Service\XlsProcessor;

/**
 * @Route(name="item.")
 */
class ItemController extends AbstractController {
    /**
     * @Route("/", name="list")
     * @Method("GET")
     * @return Response
     */
    public function list(): Response
    {
        return $this->render('item/list.html.twig');
    }

    /**
     * @Route("/download", name="generate")
     * @Method("GET")
     * @param XlsProcessor $xlsProcessor
     * @return Response
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     */
    public function generate(XlsProcessor $xlsProcessor): Response
    {
        $spreadsheet = $xlsProcessor->createSpreadSheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setCellValue(
            'A1',
            'Generated by ' . $this->getUser()->getUsername()
        );
        $fileName = $this->getUser()->getUsername() . '_' . date('dmY') . '.xls';
        $xlsProcessor->save(
            $spreadsheet,
            $fileName
        );

        $directory = $this->getParameter('xls_directory');
        return $this->file($directory . '/' . $fileName);
    }
}
