# config/packages/prod/monolog.yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            # 500 errors are logged at the critical level
            action_level: critical
            excluded_http_codes: [403]  # Probably, not working
            # to also log 400 level errors (but not 404's):
            # action_level: error
            # excluded_404s:
            #     - ^/
            handler: deduplicated
        deduplicated:
            type: deduplication
            # the time in seconds during which duplicate entries are discarded (default: 60)
            time: 60
            handler: swift
        swift:
            type: swift_mailer
            from_email: '%env(MAILER_SENDER)%'
            to_email: '%env(MAILER_RECIPIENT)%'
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            subject: 'An Error Occurred! %%message%%'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
