services:
    # This part is important!
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Use the namespace where your fixtures are
    App\DataFixtures\:
        resource: '../src/DataFixtures/*'
